name: Publish Docker image

on:
    workflow_dispatch:
        inputs:
            mumble-version:
                description: "The version (tag or commit hash) of Mumble to build"
                required: true
                default: "latest"
            docker-version:
                description: "Docker image version, independent of mumble version"
                required: true
                default: 0

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              
            - name: Set mumble-version if manual trigger
              if: "${{ github.event.inputs.mumble-version != '' }}"
              run: echo "MUMBLE_VERSION=${{ github.event.inputs.mumble-version }}" >> $GITHUB_ENV
              
            - name: Set docker-version if manual trigger
              if: "${{ github.event.inputs.docker-version != '' }}"
              run: echo "DOCKER_VERSION=${{ github.event.inputs.docker-version }}" >> $GITHUB_ENV
              
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
              
            - name: Set up Docker Build
              uses: docker/setup-buildx-action@v2
              
            - name: Login to DockerHub
              uses: docker/login-action@v2 
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                context: .
                platforms: linux/amd64
                push: true
                build-args: |
                  MUMBLE_VERSION=${{ env.MUMBLE_VERSION }}
                tags: mumblevoip/mumble-server:latest,mumblevoip/mumble-server:${{ env.MUMBLE_VERSION }},,mumblevoip/mumble-server:${{ env.MUMBLE_VERSION }}-${{ env.DOCKER_VERSION }}
